default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: integration-sample-rails-development

test:
  <<: *default
  database: integration-sample-rails_test
